---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ulake-service-acl-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ulake-service-acl
  template:
    metadata:
      labels:
        app: ulake-service-acl
    spec:
      containers:
      - name: ulake-service-acl
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.6
        command: ["/home/canhieu/ulake-service-acl-runner"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        volumeMounts:
        - name: user-acl-volume
          mountPath: /home/canhieu/ulake-service-acl-runner
      volumes:
      - name: user-acl-volume
        hostPath:
          path: /home/canhieu/ulake-internship/acl/build/acl-1.0.0-SNAPSHOT-runner

---
apiVersion: v1
kind: Service
metadata:
  name: ulake-service-acl
  namespace: default
spec:
  selector:
    app: ulake-service-acl
  ports:
  - protocol: TCP
    port: 8783
    targetPort: 8783
  type: LoadBalancer
