apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ulake-service-folder-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ulake-service-folder-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
