apiVersion: apps/v1
kind: Deployment
metadata:
  name: ulake-service-log-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ulake-service-log
  template:
    metadata:
      labels:
        app: ulake-service-log
    spec:
      containers:
      - name: ulake-service-log
        image: registry.access.redhat.com/ubi8/openjdk-11
        env:
        - name: JAVA_APP_JAR
          value: "/home/canhieu/log/quarkus-run.jar"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        volumeMounts:
        - name: user-log-volume
          mountPath: /home/canhieu/log
      volumes:
      - name: user-log-volume
        hostPath:
          path: /home/canhieu/ulake-internship/log/build/quarkus-app
---
apiVersion: v1
kind: Service
metadata:
  name: ulake-service-log
  namespace: default
spec:
  selector:
    app: ulake-service-log
  ports:
  - protocol: TCP
    port: 8790
    targetPort: 8790
  type: LoadBalancer
