apiVersion: apps/v1
kind: Deployment
metadata:
  name: ulake-nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ulake-nginx
  template:
    metadata:
      labels:
        app: ulake-nginx
    spec:
      containers:
      - name: ulake-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ulake-nginx-service
  namespace: default
spec:
  selector:
    app: ulake-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
