---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ulake-phpmyadmin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ulake-phpmyadmin
  template:
    metadata:
      labels:
        app: ulake-phpmyadmin
    spec:
      containers:
        - name: ulake-phpmyadmin
          image: phpmyadmin:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: PMA_HOST
              value: "ulake-mysql"
            - name: PMA_PORT
              value: "3306"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ulake-phpmyadmin-service
  namespace: default
spec:
  selector:
    app: ulake-phpmyadmin

  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
  type: LoadBalancer
